fieldLayouts:
  f0e88ae8-8493-4b61-9355-4b5b3df242c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e71addae-f249-4141-b5aa-3909eeeadb85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da4aef78-f7ee-4845-831d-c0a142be84d1
        userCondition: null
fs: cargas
handle: cargas
name: cargas
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
